name: Main

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/checkout@v2
      - run: terraform fmt -check -recursive -diff
